language: smalltalk
sudo: false
os:
- linux
- osx
smalltalk:
- Pharo-5.0
- Pharo-6.0

env:
  global:
  - secure: O+KogdhPw3592DTKsW9LeApL77ch3B46A/FD+IBVUjgb0sIjfdJcPm2nsThi7/7RgqQvG8P90dTJ6fAsR6IJFZhBfEeUDKanBIT1MRbnkQLRrlJ62OICjPdhu5+1vwAsIWRPkGTwgSNNbfhoeSU4hTNUYFxlM+qXG8365GWPxN4=
  - secure: fq1kZksqHvsTREEaGrDgTEkfhslD0mgpMBcLB034OyM5hfabCpcuRsx87851WVQBoCFu2AoKSBfDRNc5SWN2cQJf9tjRLxzGKio/6/X43vSLLT/w0V6/saeGHmZZeCCVbukruFTaYjBEWCbO708c1A/Scs2nIyw7dHyMyHVGjPU=


deploy:
  provider: script
  skip_cleanup: true
  script: ".utility/flatDeploy.sh"
  on:
    smalltalk: Pharo-6.0
    condition: "$TRAVIS_OS_NAME = osx"
    all_branches: true
    tags: true
