language: smalltalk
sudo: false
os:
- linux
- osx
smalltalk:
- Pharo-5.0
- Pharo-6.0
env:
  global:
  - secure: gpUoXv7DGhyO0FWIhvDINhxd6xGu12mTqn5v4ZLNdUX2Yx7Kwg1H95BGQUEocKWTCksko1c3mp7+xbLP8vGxmP1mSw1UOkN5ZwlNBjvWjACY1ehyttLHaIu46qVCu960GSV2fwKhVjzmzXspoWHTaptpwlN4y8jQkzPRTGkm8HM=
  - secure: z3CXmIrSr+09VG8cB6qzLd8kON1kve4OKy55UAlVpZvpZ2pGwkbw79QTA7baPm2MadxmRFaFiBK5ONlVU07232gIjsd0LDlZQ6ouScdHBK7jSYy2isG8212sEIlJoVhKh0lrrIE0Zac8zVGYmpHzvRZWCyDw2tnzoS2G1SvwGS8=

deploy:
  provider: script
  skip_cleanup: true
  script: .utility/flatDeploy.sh
  on:
    smalltalk: Pharo-5.0
    os: osx
    all_branches: true